- lusidtools/lpt/qry_scopes.py
The list_portfolios endpoint now returns 5000 portfolios max by default.
If there are more than 5000 portfolios, this enhancement will page-in
the remainder.
> Add pagination to qry_scopes

- docs/source/conf.py
- lusidtools/apps/upsert_instruments.py
The Readthedocs build is getting sphinx error (still builds fine locally). This change explicitly states the name of the master document for the documentation to be called `index.rst` and not `contents.rst`.
A link to the suggested fix is provided here:
https://github.com/readthedocs/readthedocs.org/issues/2569
error:
```
Sphinx error:
master file /home/docs/checkouts/readthedocs.org/user_builds/lusidtools/checkouts/latest/docs/source/contents.rst not found
```
> DEV-7530: Add master_doc parameter to Docs conf.py

- lusidtools/cocoon/utilities.py
- tests/unit/cocoon/test_utilities.py
DEV-7563: Add Check for empty string
This PR Fixes an underhanded error when an empty string is passed in the mapping
> DEV-7563: Add check for empty mapping string

- lusidtools/cocoon/cocoon_printer.py
- tests/unit/cocoon/test_cocoon_printer.py
Checks each row in output dataframe contains some correct data against provided ground truth value
DEV-7602: Fixed cocoon printer returning nan
For quotes and instruments
Fixed printer bug where format_instruments_response and format_quotes_response returned NaN instead of the instrument IDs.
> DEV-7602: Fixed cocoon printer returning nan

- lusidtools/lpt/dfq.py
- lusidtools/lpt/lse.py
If we use the dfq filter and use any option that
refers to the input, an exception is thrown.
e.g.
to only show the first 5 records,
xxxx --dfq -f 5
This fix will prevent that from happening.
Also, remove references to msrest in lse.py
These are causing warnings in pytest
> DEV-7768: Bugfix - dfq filter options

- lusidtools/lpt/lpt.py
Metric property values were being created as the string 'nan' 
Check for empty values in a dataframe using pd.isna() instead of comparison with None
> DEV-7819: Deal with Null property values as 'nan'

- lusidtools/cocoon/utilities.py
- tests/unit/cocoon/test_utilities.py
- Raise an exception if no transactions exists as per the specified
fx forward transaction type code for default_FX_forward_model method
- Add test case to ensure exception raised as per requirement above.
> DEV-7676 Adding validation checks in default_FX_forward_model

- lusidtools/lpt/lpt.py
- tests/unit/lpt/test_lpt.py
- Adding support into read_input for Windows paths. Previously issue in
the need to support an excel path with a sheet name suffixed via ":"
which failed with Windows absolute paths due to the drive specifier ":"
- Now check for an excel file with sheet via a regex to check for the
complete excel file type and ":". Also solves the problem of potential
issues with unix files named with a ":".
> DEV-8104 Adding Windows path support for read_input

- lusidtools/cocoon/cocoon_printer.py
- tests/unit/cocoon/test_cocoon_printer.py
SE-100: Added a formatting function in cocoon_printer for reference portfolios. Tests also added in test_cocoon_printer.
https://finbourne.atlassian.net/browse/SE-100
> Feature/se 100.format reference portfolios response

- lusidtools/cocoon/seed_sample_data.py
- tests/integration/cocoon/data/seed_sample_data/seed_sample_data_override.json
- tests/integration/cocoon/test_seed_sample_data.py
When explicitly passing in a mapping to `seed_data` this commit defaults any optional mappings to an empty dict/list if one is not provided. This is a requirement of lpt rather than a requirement of the core API. 
https://finbourne.atlassian.net/browse/SE-146
> Feature/se 146.seed data optional mappings default

- lusidtools/cocoon/utilities.py
- tests/integration/cocoon/test_cocoon_holdings.py
Allows for hard-coded integers to be passed as integers into LTP mappings, rather than as strings with the $ constant prefix.
> Feature/se 275.lpt accept hardcoded int

- lusidtools/apps/__init__.py
- lusidtools/apps/upsert_instruments.py
- lusidtools/apps/upsert_portfolios.py
- lusidtools/apps/upsert_quotes.py
- lusidtools/apps/upsert_transactions.py
- lusidtools/cocoon/utilities.py
- setup.py
- tests/integration/apps/test_command_line_apps.py
- tests/integration/apps/test_data/mapping_port.json
DEV-189: update tests
- Adds the property scope argument to the command line apps, which defaults to the scope argument if not specified 
- Updates the optional load from dataframe parameters with dict.get([something], [default])
- Adds a command line app to create portfolios
> SE-189: Add Upsert Portfolio to command line apps & update existing apps

- lusidtools/lpt/search_instruments.py
- tests/integration/cocoon/test_cocoon_instruments.py
- tests/integration/cocoon/test_cocoon_portfolios.py
- tests/unit/pandas_utils/test_lusid_pandas.py
- Fix search instruments - replace symbols parameter with instrument_search_property
- Fix error message for LUSID exceptions - 'All items in list must be of the same data type'
- Added Test for upsert Lookthough portfolio ID
- Update cocoon upsert portfolio with invalid scope failure test (used to return 400, now it returns lusid.exceptions.ApiValueError)
> SE-454: Add Test for upsert Lookthough portfolio ID

- .github/workflows/cron.yaml
The job should timeout if tests take more than 30 mins
> Add timeout of 30 mins to cron

- lusidtools/cocoon/utilities.py
- tests/unit/cocoon/data/global-fund-fixed-income-master.csv
- tests/unit/cocoon/test_cocoon_complex_instrument.py
SE-610: Adding support complex instruments in load_from_data_frame
- [ x ] Read the [contributing guidelines](https://github.com/finbourne/lusid-python-tools/blob/master/docs/CONTRIBUTING.md)
- [ x ] Tests pass
- Added support for Bond Instrument definition to ```load_from_data_frame```
- Tests passed
> SE-610: Adding support for bond instrument in load_from_data_frame

- tests/integration/cocoon/test_seed_sample_data.py
- [ x ] Read the [contributing guidelines](https://github.com/finbourne/lusid-python-tools/blob/master/docs/CONTRIBUTING.md)
- [ x ] Tests pass
- Removed problematic `from_transactions_date` parameter
- Added tearDown class to remove test portfolios
> SE-755: Removed transaction date lower bound for transactions test.

- lusidtools/cocoon/cocoon_printer.py
- tests/integration/cocoon/data/cocoon_format_portfolio_errors.csv
- tests/integration/cocoon/test_cocoon_printer.py
- tests/unit/cocoon/test_cocoon_printer.py
This PR will add a flag to the cocoon printer formatting methods to enable extended error message reporting. 
By default the behavior is the same as before. With the new flag being passed, the errors in the response formatting will include the RequestIds and the ErrorDetails to help the user identify potential issues faster.
> SE-1201: Added flag for extended errors in cocoon printer

- lusidtools/cocoon/cocoon.py
- tests/integration/cocoon/test_cocoon_holdings.py
- tests/integration/cocoon/test_cocoon_transactions.py
A recently added flag within `load_from_data_frame()` called `return_unmatched_identifiers` was useful in showing which instrument identifiers did not resolve when uploading transactions or holdings, but there was not always enough information to be able to quickly identify which transactions or holdings were affected. 
This change renames that feature flag to `return_unmatched_items` and updates the logic so that the entire transaction or holding object is returned when the instrument does not successfully resolve in LUSID. This will give all users all the information they require to quickly identify which items in their upload did not resolve, as well as providing them with helpful associated metadata that they can use to improve their workflow to correct the identifiers.
> Feature/se 1284.return full response

- lusidtools/lpt/dfq.py
- lusidtools/lpt/lse.py
- tests/integration/cocoon/test_async_tools.py
Currently the dfq -w argument only supports exact = and ! 
This PR extents that functionality to include <, >, <=, >= to allow queries like 
-w "diff_cost<3" "diff_cost>-3" "Transaction/SHK/CATEGORY!=Investments Long"
(where the diff is between -3 and 3, and CATEGORY is not "Investments Long")
> SE-1326: Extend DFQ where functionality

- lusidtools/cocoon/cocoon.py
- tests/integration/cocoon/test_cocoon_holdings.py
If a load_from_data_frame encounters an error with a holdings upload, the return_unmatched_items logic (if a True parameter is provided) may obscure the load error by raising it's own exception. The return_unmatched_items error should be handled gracefully and the main lusid error should returned as normal to the user so that they can debug the primary issue.
> SE-1323: Handle getholding lusid exception within LPT

- lusidtools/cocoon/cocoon.py
- tests/integration/cocoon/data/holdings-example-duplicate-shk.csv
- tests/integration/cocoon/data/holdings-example-single-holding.csv
- tests/integration/cocoon/test_cocoon_holdings.py
If any errors are present in an upload using `load_from_data_frame`, the upload validation logic in `return_unmatched_items` will not be run, even if the flag is passed. All errors will be handled and returned to the user.
> SE-1437: Do not validate upload if any errors

- lusidtools/cocoon/cocoon.py
- lusidtools/cocoon/properties.py
- lusidtools/cocoon/validator.py
- tests/integration/cocoon/test_cocoon_holdings.py
- tests/integration/cocoon/test_cocoon_portfolios.py
- tests/integration/cocoon/test_cocoon_transactions.py
- tests/integration/extract/test_group_holdings.py
- tests/unit/cocoon/test_properties.py
- tests/unit/cocoon/test_validator.py
Basically lets you pass in property columns like this:
`"column1"`
or
`{"source": "column1", "target": "myAwesomeColumn", "scope": "mySuperScope"}`
You can mix dictionaries and strings in the same list.
If you don’t provide target it will use `source` as property code. If you don’t provide scope it will use `properties_scope` as the scope.
> SE-165: More configurable property_columns

- lusidtools/lpt/dfq.py
- lusidtools/lpt/qry_properties.py
- lusidtools/lpt/txn_config_yaml.py
- requirements.txt
- tests/integration/cocoon/test_create_transaction_type.py
- tests/integration/cocoon/test_upsert_transaction_type_alias.py
- tests/integration/commands/test_commands.py
Tests were failing in part because an outdated lusid-python-sdk was being used. This change includes an update to the requirements file.
A new model for `transaction_configuration_type_alias` included a new parameter (`source`) which was throwing off a number of tests that expected either the old model or one fewer parameter. 
Also fixed two other tests and added a skip flag to the `properties_search` test that needs further investigation. The functionality being tested has been commented out and a Jira has been raised to investigate.
> Feature/SENG-37: Update lusid sdk version and fix tests

- lusidtools/cocoon/cocoon.py
In the merge request to add support for [configurable property columns](https://github.com/finbourne/lusid-python-tools/pull/225) we added an arbitrary 5 second timeout on calls to `SetHoldings` and `AdjustHoldings`.
These were included in error and need to be removed to allow for calls which take 5 seconds or longer to be successful.
> SE-1923 Remove arbitrary request timeout included in err

- tests/integration/cocoon/test_async_tools.py
Temporarily disable the load test whilst we investigate the timeouts
> temporarily disable test

- lusidtools/apps/flush_transactions.py
- lusidtools/lpt/stdargs.py
- requirements.txt
- tests/integration/apps/test_command_line_apps.py
- tests/unit/apps/test_command_line_utilities.py
Changing the flush_transactions LPT app so that it can take a scope and flush all transactions for portfolios in the scope. 
This is a breaking change as the portfolio argument was previously required and is now optional and must be proceeded with a `-p` flag. 
To add some level of protection when flushing, an additional flag `--flush_scope` must be passed if all portfolios in the scope are to be flushed.
> Ctech 1363 flush transactions can flush for all portfolios in scope

- lusidtools/cocoon/utilities.py
This is a one line fix. I believe the issue is due to whether a data frame is a copy or a view. If the data frame is a view then it acts like a reference to the original data frame, so any changes will affect both data frames. This becomes an issue when we pass in the data_frame.loc[...], since loc can either return a copy of a data frame or a view of it depending on the memory. When we make assignments to columns of the data frame pandas warns us since it thinks we want to assign to a view when the data frame is actually a copy.
To ensure that the data frame is a copy, we just assign it to be the copy of itself at the start of the function.
> feature/CTECH-308: resolved SettingWithCopyWarning.

- lusidtools/cocoon/cocoon.py
- tests/integration/cocoon/data/no-subholding-keys-transactions.csv
- tests/integration/cocoon/test_cocoon_transactions.py
transactions when they don't exist on the portfolio.
just added some lines to the function that checks when the sub_holding_key variable is not empty (for transactions) and creates a property for it, if it doesn't exist. Then adds the properties as subholding keys to the parent portfolios of the transactions.
I also added a test which checks whether the sub_holding_key exists on the portfolio after running the function with transaction data and tests that the properties were added to the transactions.
> feature/CTECH-177: load_from_data_frame now creates sub_holding_keys for

- lusidtools/cocoon/properties.py
Moves cocoon properties from using deprecated iteritems to items.
- [ x ] Read the [contributing guidelines](https://github.com/finbourne/lusid-python-tools/blob/master/docs/CONTRIBUTING.md)
- [ x ] Tests pass
> SE-2734: Fixed iteritems to items

- tests/integration/cocoon/test_create_transaction_type.py
- tests/integration/cocoon/test_upsert_transaction_type_alias.py
Update transaction config to use its own `source` to avoid clashes with other uploaded data
> CTECH-2310 update source for txn config tests
