lusidtools/cocoon/cocoon.py, lusidtools/cocoon/utilities.py, tests/unit/cocoon/test_utilities.py
- remove_whitespace now only acts upon a list of specified columns
- used df.apply() to speed function up
- moved remove_whitespace call in Load_from_data_frame() to after parameter checks
=> DEV-5880: edit remove_whitespace() to take columns of interest

lusidtools/lpt/txn_config_yaml.py, tests/integration/commands/test_commands.py
Fix transaction config editing
=> DEV-5967 Fix transaction editing

lusidtools/cocoon/__init__.py, lusidtools/cocoon/cocoon.py, lusidtools/cocoon/instruments.py, lusidtools/cocoon/utilities.py, tests/unit/cocoon/test_utilities.py
- [ x] Read the [contributing guidelines](https://github.com/finbourne/lusid-python-tools/blob/master/CONTRIBUTING.md)
- [x ] Tests pass
=> Feature/dev 6407.clean up and improve tests

setup.py, tests/unit/cocoon/test_utilities.py
update SDK version in setup.py and force black formatting
=> DEV-6210: Update SDK version in setup.py

tests/integration/cocoon/test_utilities.py
=> Force Black formatting

tests/integration/cocoon/test_utilities.py
=> DEV-6210: Add invalid formatting to trigger black formatting and publish

setup.py
=> adding json_flatten to setup

lusidtools/pandas_utils/lusid_pandas.py, tests/unit/pandas_utils/test_lusid_pandas.py
=> DEV-6664 formatter

lusidtools/lpt/stdargs.py, tests/integration/lpt/examples/example-tr-file.json, tests/unit/cocoon/test_utilities.py
=> Replace references in test

lusidtools/lpt/create_properties.py
=> DEV-5949: migrate  DataType scope

lusidtools/cocoon/cocoon.py
=> remove auto logging

lusidtools/cocoon/cocoon_printer.py
For quotes, I want to return the flattened **Value** rather than the **Key**.
This provides more information to the end-user.
**Key**
`{'LUID_8LUYNBXW_LusidInstrumentId_2019-01-02T00:00:00Z': 
`
Example **Value** for a dict with same key
```
{
'as_at': datetime.datetime(2020, 3, 16, 14, 26, 41, 947540, tzinfo = tzutc()),
'cut_label': '',
'lineage': '',
'metric_value': {
'unit': "USD",
'value': "155.582367"
},
'quote_id': {
'effective_at': '2019-01-02T00:00:00.0000000+00:00',
'quote_series_id': {
'field': 'mid',
'instrument_id': 'LUID_8LUYNBXW',
'instrument_id_type': 'LusidInstrumentId',
'price_source': None,
'provider': 'DataScope',
'quote_type': 'Price'
}
},
'uploaded_by': '00u681arbmRvUDxQN2p7'
}
}
```
=> extend printer functionality

README.md
=> DEV-6849 update readme

lusidtools/cocoon/transaction_type_upload.py, tests/integration/cocoon/test_create_transaction_type.py
=> add transaction upload

tests/unit/cocoon/test_utilities.py
Update tests as transaction price no longer mandatory
=> DEV-6442 transaction price no longer optional

docs/Makefile, docs/make.bat, docs/source/conf.py, docs/source/index.rst, lusidtools/cocoon/async_tools.py, lusidtools/cocoon/cocoon.py, lusidtools/cocoon/cocoon_printer.py, lusidtools/cocoon/dateorcutlabel.py, lusidtools/cocoon/instruments.py, lusidtools/cocoon/properties.py, lusidtools/cocoon/seed_sample_data.py, lusidtools/cocoon/systemConfiguration.py, lusidtools/cocoon/transaction_type_upload.py, lusidtools/cocoon/utilities.py, lusidtools/cocoon/validator.py, lusidtools/pandas_utils/lusid_pandas.py
DEV-7441: Update docstrings - async_tools.py
DEV-7441: Update docstrings - cocoon.py
DEV-7441: Update docstrings - cocoon_printer.py
DEV-7441: Update docstrings - instruments.py
DEV-7441: Update docstrings - properties.py
DEV-7441: Update docstrings - utilities.py
DEV-7441: Update docstrings - validator.py
Replaces restructured text docstring format with numpy format. 
see [this](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html) for an example
=> DEV-7441: Update docstrings to Numpy format

lusidtools/cocoon/utilities.py
This PR encapsulates the time-based ID creation into another function, not specific to scope. Create_scope_id is left as a shell for compatibility with existing usages
=> DEV-6172: Refactor create_scope_id into shell function

lusidtools/pandas_utils/lusid_pandas.py, tests/unit/pandas_utils/test_lusid_pandas.py
=> pandas utils: handle empty lists

lusidtools/data/order-example.csv, lusidtools/lpt/create_instr.py, lusidtools/lpt/create_orders.py, lusidtools/lpt/lpt.py, tests/integration/lpt/examples/orders.csv, tests/integration/lpt/test_lpt.py
New lusidtools tool to create orders. Reads an order per row from a csv file.
=> WIP: DEV-7805: first cut of order creation tool

lusidtools/cocoon/utilities.py, tests/integration/apps/test_command_line_apps.py, tests/integration/cocoon/test_instruments.py, tests/unit/apps/test_command_line_utilities.py, tests/unit/cocoon/test_cocoon_printer.py, tests/unit/cocoon/test_utilities.py
=> DEV-8199: Remove column in identify_cash_items where remove == True

README.md, lusidtools/pandas_utils/lusid_pandas.py
=> bump version test

README.md, ci_tools/bumpversion.sh, lusidtools/pandas_utils/lusid_pandas.py
=> test of bump version

.travis.yml, README.md, lusidtools/pandas_utils/lusid_pandas.py
=> amend travis to prevent duplicate deployment

ci_tools/bumpversion.sh
=> amending bump version to prevent duplicate version commits

lusidtools/lpt/map_instruments.py, lusidtools/lpt/stdargs.py
=> DEV-8260: Fix map Instruments Bug in LPT

lusidtools/lpt/create_properties.py, lusidtools/lpt/qry_transactions.py
=> DEV-8477: Update LPT create_properties & qry_transactions

lusidtools/lpt/create_group_portfolios.py, lusidtools/lpt/qry_aggregate_holdings.py, lusidtools/lpt/upload_quotes.py
=> DEV-8350: Fix LPT methods used by initial-data-load

lusidtools/lpt/qry_aggregate_holdings.py, requirements.txt, tests/integration/lpt/test_lpt.py
=> DEV-8665 Rename deprecated aggregation function

lusidtools/jupyter_tools/__init__.py, lusidtools/jupyter_tools/hide_code_button.py, lusidtools/lpt/qry_aggregate_holdings.py, tests/integration/lpt/test_lpt.py, tests/unit/jupyter_tools/test_hide_code_button.py
=> toggle code nb

lusidtools/jupyter_tools/hide_code_button.py, tests/unit/jupyter_tools/test_hide_code_button.py
=> toggle code

lusidtools/lpt/qry_aggregate_holdings.py, lusidtools/lpt/txn_config.py
=> DEV-8335: Aggregation Api changes

lusidtools/lpt/get_instruments.py, lusidtools/lpt/qry_instruments.py, lusidtools/lpt/qry_properties.py, lusidtools/lpt/qry_transactions.py
=> DEV-8567: 3.1 API updates

lusidtools/cocoon/utilities.py, tests/unit/cocoon/test_utilities.py
=> DEV-6172: Add UUID generator to Create scope ID

lusidtools/lpt/lpt.py, lusidtools/lpt/upload_hld.py
Remove an unreachable line of code from the LPT, as identified by sonarcloud: https://sonarcloud.io/project/issues?id=finbourne_lusid-python-tools&issues=AXDj4zMMVTrHlXshBRYj&open=AXDj4zMMVTrHlXshBRYj
=> SE-93: removed unreachable code

lusidtools/cocoon/transaction_type_upload.py, tests/integration/cocoon/test_replace_current_transaction_alias.py, tests/integration/cocoon/test_upsert_transaction_type_alias.py
=> upsert txn type

features/main.py, lusidtools/lpt/back_compat.py, lusidtools/lpt/cash_ladder.py, requirements.txt
=> Feature/se 306.lpt feature runner

lusidtools/lpt/create_group_portfolios.py
=> SE-443: Add created date parameter to CreateGroupPortfolios in the CLI

lusidtools/lpt/create_group_portfolios.py
=> SE-443: Add default value for created date in create portfolio group

tests/integration/cocoon/test_async_tools.py
=> SE-463: disabling test which is causing performance issues

tests/integration/cocoon/test_async_tools.py
=> SE-463: Temp remove of async tests

tests/integration/cocoon/test_async_tools.py
=> SE-463: Re-enable async tests

.github/workflows/run-tests-on-pull.yml, ci_tools/new_commit_with_black.sh, tests/unit/pandas_utils/test_lusid_pandas.py
=> Enabling black

.github/workflows/cron.yaml
Adding cron job for daily tests
=> SE-462: Adding daily cron job for tests

.github/workflows/cron.yaml
=> SE-462: amend cron job

.github/workflows/slack-on-pr.yml
=> SE-545: add slack alert on PR

lusidtools/cocoon/utilities.py, tests/integration/cocoon/data/lookthrough_instr_tests/load_lookthrough_instrument.csv, tests/integration/cocoon/data/lookthrough_instr_tests/mixed_instruments_default_scope.csv, tests/integration/cocoon/data/lookthrough_instr_tests/mixed_lookthrough_instruments.csv, tests/integration/cocoon/data/lookthrough_instr_tests/mixed_lookthrough_instruments_multiple portfolios.csv, tests/integration/cocoon/data/lookthrough_instr_tests/multiple_instruments_with_same_portfolio.csv, tests/integration/cocoon/test_cocoon_instruments.py, tests/unit/cocoon/test_utilities.py
Added support for loading mixed dataframes of instruments with and without looktrhough instruments 
Added Integration tests for this
added test case for set_attributes() for an instrument definition without a lookthrough instrument
updated test names for set_attributes()
Github actions from @slemasne  (check if these are still relevant, have they already been added to master?)
=> Feature/se 465.mixed lookthrough instruments

tests/integration/cocoon/test_async_tools.py, tests/integration/cocoon/test_cocoon_failures.py, tests/integration/cocoon/test_cocoon_holdings.py, tests/integration/cocoon/test_cocoon_instruments.py, tests/integration/cocoon/test_cocoon_portfolio_groups.py, tests/integration/cocoon/test_cocoon_portfolios.py, tests/integration/cocoon/test_cocoon_quotes.py, tests/integration/cocoon/test_cocoon_transactions.py, tests/integration/cocoon/test_create_transaction_type.py, tests/integration/cocoon/test_instruments.py, tests/integration/cocoon/test_reference_portfolios.py, tests/integration/cocoon/test_seed_sample_data.py, tests/integration/cocoon/test_upsert_transaction_type_alias.py, tests/integration/cocoon/test_utilities.py
Annotates all cocoon test features with lusid_feature decorators
=> SE-306 annotates all cocoon tests with Lusid Features

.github/workflows/cron.yaml, .github/workflows/run-tests-on-pull.yml, README.md
Updates to make GHA naming consistent with other packages.
=> SE-621: Update to GHA

.github/workflows/slack-on-issue.yml
Add slack for new or edited issue.
=> SE-633: add slack for issues

.github/workflows/slack-on-issue.yml
Updating slack channel for GHA issue notification.
=> SE-633: Updating GitHub actions

lusidtools/lpt/qry_aggregate_holdings.py, tests/integration/lpt/test_lpt.py
adds the --prop parameter that requests properties to the aggregate lusidtools command
=> SE-572: Add property parameter to qry_aggregate_holdings

lusidtools/lpt/dfq.py, lusidtools/lpt/get_instruments.py, lusidtools/lpt/lpt.py, lusidtools/lpt/lse.py, lusidtools/lpt/pager.py, lusidtools/lpt/qry_instruments.py, lusidtools/lpt/qry_portfolios.py, lusidtools/lpt/qry_scopes.py, lusidtools/lpt/qry_target_holdings.py, lusidtools/lpt/search_instruments.py, lusidtools/lpt/txn_config_yaml.py
Misc small enhancements
Show the insights link when displaying an error.
Display stats of each request if the --stats argument is used
Preserve all properties in txn_cfg
effective date parameter for search_instruments
effective date parameter for get_instruments
show as-at date in target holdings
paging in qry_scopes
paging in qry_portfolios
paging in qry_instruments
int conversion option in dfq
=> DEV-10721: Show Insights link in error + misc

lusidtools/lpt/qry_quotes.py, lusidtools/lpt/txn_config.py
Adds asat option to the txn_cfg
Also, updates the quotes query to reflect parameter name change
=> DEV-10920: AsAt option on txn_cfg

lusidtools/lpt/qry_aggregate_holdings.py
=> DEV-10956: Fix parameter name in PortfolioEntityIds

lusidtools/lpt/qry_aggregate_holdings.py
=> DEV-10956: Fix aggregation parameters

lusidtools/cocoon/cocoon.py, tests/integration/cocoon/test_cocoon_holdings.py
Returns unmatched identifiers for holdings in groups of identifiers
=> SE-1134.2: Option 2

lusidtools/cocoon/cocoon.py
This PR adds a couple of debug statements that I found useful for diagnosing performance issues related to batch loading of large data loads.
- When a batch gets sent
- When the response is completed
- The end to end duration of the request
=> SE-1487: Add debug statements around batch requests 

lusidtools/lpt/connect_lusid.py, tests/integration/lpt/test_lpt.py, tests/unit/lpt/test_connect_lusid.py
=> Add error message if config and secrets are missing

lusidtools/apps/upsert_quotes.py, tests/integration/apps/test_command_line_apps.py, tests/integration/apps/test_data/mapping_quote_no_cash_flag.json, tests/integration/apps/test_data/quotes_minimal.csv
=> SE-1573: Check existence of cash_flag before filtering quotes

tests/integration/lpt/test_lpt.py, tests/unit/lpt/test_connect_lusid.py
=> fixing bug with the test for missing config file

README.md
=> added full stop

README.md
Added 2 full stops to the README.md
=> SE-1720 Full stops added, rh

lusidtools/lpt/dfq.py, lusidtools/lpt/lpt.py, requirements.txt, tests/integration/cocoon/test_seed_sample_data.py, tests/unit/lpt/test_lpt.py
=> SE-650: Switch xlrd to openpyxl

lusidtools/lpt/dfq.py, tests/unit/lpt/test_dfq.py
=> SE-1589: Exit dfq if we don't have a DataFrame

lusidtools/cocoon/cocoon.py, lusidtools/cocoon/properties.py, tests/integration/cocoon/test_cocoon_portfolios.py, tests/integration/cocoon/test_cocoon_transactions.py, tests/unit/cocoon/test_properties.py
=> Properties bug

requirements.txt
Relax the version requirements on pandas to allow for later versions to be used
=> SE-1867 Relax requirement on pandas version

.github/workflows/bump-version-and-publish.yml, .github/workflows/cron.yaml, .github/workflows/run-tests-on-pull.yml, .github/workflows/slack-on-pr.yml
- Use requirements.dev
- Remove referenece to develop branch
- Remove awscli install
- Add note on v2 master branch
- Reduced timeout on tests from 60 to 30 (they currently run in c.11 mins)
=> SENG-38: Github actions updates

lusidtools/lpt/qry_transactions.py
=> DEV-11849: Paging for Transactions

setup.py
Pinning the version of openpyxl to `setup.py`.
=> SENG-154: Add openpyxl to setup.py

lusidtools/apps/flush_transactions.py, lusidtools/lpt/stdargs.py, tests/integration/apps/test_command_line_apps.py, tests/integration/cocoon/test_async_tools.py, tests/unit/apps/test_command_line_utilities.py, tests/unit/apps/test_data/test_transactions.py
Adds portfolio group functionality to the flush_transactions app.
=> Feature/ctech 591.flush groups

tests/integration/apps/test_command_line_apps.py
Reduced transaction count in flush tests to reduce time it takes for these to run
=> Feature/ctech 690.reduce test transactions

requirements.txt
Update urllib3 via transitive dependency of requests
=> CTECH-1368 update request/urllib3

lusidtools/cocoon/cocoon.py, lusidtools/cocoon/utilities.py, tests/integration/cocoon/test_cocoon_instruments.py
=> feature/SE-2251: Update - update instrument upsert to include scope

lusidtools/cocoon/cocoon.py, lusidtools/cocoon/utilities.py, tests/integration/cocoon/test_cocoon_instruments.py
Reverts finbourne/lusid-python-tools#266
=> Revert "feature/SE-2251: Update - update instrument upsert to include scope"

docs/CONTRIBUTING.md
=> I added a full stops to lines in CONTRIBUTING.md

.bumpversion.cfg, ci_tools/bumpversion.sh
https://github.com/finbourne/lusid-python-tools/commit/d3df1127d53b4e4e5688f94a3f3229e67800a868 needed a corresponding change to the bump2version config
=> CTECH-2023 fix bump2version config

lusidtools/cocoon/utilities.py, lusidtools/cocoon/validator.py, tests/integration/apps/test_command_line_apps.py, tests/integration/apps/test_data/mapping_trans_invalid_empty_column.json
=> SE-198: validate empty field mapping

tests/integration/iam/test_iam_roles.py
This needs doing following a failure we observed on the daily build: https://github.com/finbourne/lusid-python-tools/actions/runs/3654341309/jobs/6180394621#step:5:2091
=> CTECH-2361: Add a try/except around the delete role call incase the role doesn't exist

README.md, docs/CONTRIBUTING.md
- Updated contributing guide to match process and README.md to signpost
=> CTECH-777 contributing guide updates

Dockerfile, requirements.txt, setup.py
=> CTECH-2456: removed msrest and boto3 from requirements

lusidtools/cocoon/instruments.py, tests/integration/cocoon/test_seed_sample_data.py
Fix instrument id type to be str which is failing validation in the SDK
=> CTECH-2727 fix instruments id type 

Dockerfile
Updates Dockerfile to Python 3.11.2.
=> CTECH-873: update python version to 3.11.2

.github/pull_request_template.md, tests/unit/cocoon/test_utilities.py
Add priviledged information reminder to PR checklist
=> CTECH-3241: Add priviledged information reminder to PR checklist

requirements.txt
Pin Identity and Access versions < 2
=> CTECH-3395 Update requirements.txt
